## verify_pefa(): the exported integrity checker (plan sections 3.4 and 6.1).
##
## Every object tested here is a REAL pefa() result. The claim under test is
## that an object the package actually issued verifies against the installed
## package, which a hand-built list cannot demonstrate -- it would only prove
## that the checker agrees with the fixture that was written for it. The fit is
## therefore kept tiny (single spike, N = 40, J = 6, W = 3) rather than faked.
##
## NAMESPACE is regenerated by the integrator from the @export tag, so the
## function is reached through ::: here; that resolves whether or not the
## regeneration has happened yet.

.vfy <- vbpm:::verify_pefa

.vfy_data <- function(N = 40, J = 6, seed = 11) {
  set.seed(seed)
  group <- rep(1:2, each = J / 2)
  loading <- matrix(0, J, 2)
  loading[cbind(seq_len(J), group)] <- .8
  Y <- matrix(rnorm(N * 2), N, 2) %*% t(loading) +
    matrix(rnorm(N * J, sd = sqrt(1 - .64)), N, J)
  Q0 <- matrix(-1L, J, 1)
  Q0[1:2, 1] <- 1L
  list(Y = Y, Q0 = Q0)
}

.vfy_dat <- .vfy_data()
## The aggregate component-status warning is a property of the sweep, not of
## the verifier, and is tested in test-pefa-object.R.
.vfy_obj <- suppressWarnings(
  pefa(.vfy_dat$Q0, .vfy_dat$Y, 1, 3, v0 = .001, max_it = 300, verbose = FALSE)
)

## Byte image of an object, for the no-mutation checks.
.vfy_image <- function(x) serialize(x, NULL)

test_that("a real current-schema object verifies with and without Y", {
  expect_true(.vfy(.vfy_obj))
  expect_true(.vfy(.vfy_obj, .vfy_dat$Y))
  expect_invisible(.vfy(.vfy_obj))
  expect_invisible(.vfy(.vfy_obj, .vfy_dat$Y))
})

test_that("verification never mutates its input", {
  before <- .vfy_image(.vfy_obj)
  .vfy(.vfy_obj)
  .vfy(.vfy_obj, .vfy_dat$Y)
  expect_identical(.vfy_image(.vfy_obj), before)

  ## A failing call must be just as inert as a passing one.
  damaged <- .vfy_obj
  damaged$persistence$phi_min[1] <- 0.5
  damaged_before <- .vfy_image(damaged)
  expect_error(.vfy(damaged))
  expect_identical(.vfy_image(damaged), damaged_before)
})

test_that("a mutated scientific payload fails, naming the component", {
  ## $Q0 has its own fingerprint, so it is named directly rather than through
  ## the aggregate evidence hash.
  bad <- .vfy_obj
  bad$Q0[1, 1] <- 0L
  expect_error(.vfy(bad), "`$Q0` does not reproduce", fixed = TRUE)

  bad <- .vfy_obj
  bad$settings$tau <- 0.6
  expect_error(.vfy(bad), "`$settings` does not reproduce", fixed = TRUE)

  ## A moved loading is caught by the rebuild, whose message names every
  ## component the rebuilt table was built from.
  bad <- .vfy_obj
  bad$loadings[[1]][1, 1] <- bad$loadings[[1]][1, 1] + .5
  expect_error(.vfy(bad), "`$persistence` disagrees with the table rebuilt",
               fixed = TRUE)
  expect_error(.vfy(bad), "`$loadings`", fixed = TRUE)

  bad <- .vfy_obj
  bad$pips[[2]] <- bad$pips[[2]] * 0.5
  expect_error(.vfy(bad), "column `pip_rmsd` differs beyond tolerance",
               fixed = TRUE)
  expect_error(.vfy(bad), "`$pips`", fixed = TRUE)

  bad <- .vfy_obj
  bad$persistence$phi_min[1] <- 0.5
  expect_error(.vfy(bad), "`$persistence` disagrees with the table rebuilt",
               fixed = TRUE)

  bad <- .vfy_obj
  bad$transitions$ELBO_gain[1] <- 1
  expect_error(.vfy(bad), "`$transitions` disagrees with the table rebuilt",
               fixed = TRUE)

  bad <- .vfy_obj
  bad$sweep$ELBO[1] <- bad$sweep$ELBO[1] - 1
  expect_error(.vfy(bad), "`$transitions` disagrees with the table rebuilt",
               fixed = TRUE)

  ## Every one of those also breaks the sealed payload hash.
  bad <- .vfy_obj
  bad$sweep$BIC[1] <- bad$sweep$BIC[1] + 1
  expect_error(.vfy(bad), "`$provenance$evidence_sha256` does not match",
               fixed = TRUE)
})

test_that("the lineage declaration is protected separately", {
  ## Changing the declaration leaves the evidence hash alone, so the lineage
  ## check is the only one that fires and it names the three lineage fields.
  bad <- .vfy_obj
  bad$provenance$newly_fitted_K <- c(1L, 2L, 3L, 4L)
  expect_error(.vfy(bad), "`$provenance$lineage_sha256` does not match",
               fixed = TRUE)
  expect_error(.vfy(bad), "failed 1 integrity check", fixed = TRUE)

  bad <- .vfy_obj
  bad$provenance$parent_evidence_sha256 <- strrep("a", 64L)
  expect_error(.vfy(bad), "`$provenance$lineage_sha256` does not match",
               fixed = TRUE)

  bad <- .vfy_obj
  bad$provenance$reused_K <- 1L
  expect_error(.vfy(bad), "`$provenance$lineage_sha256` does not match",
               fixed = TRUE)
})

test_that("only the current schema and engine are accepted", {
  bad <- .vfy_obj
  bad$provenance$evidence_schema_id <- "vbpm_pefa_evidence_0"
  expect_error(.vfy(bad),
               "`$provenance$evidence_schema_id` is \"vbpm_pefa_evidence_0\"",
               fixed = TRUE)
  expect_error(.vfy(bad), "vbpm_pefa_evidence_1", fixed = TRUE)

  bad <- .vfy_obj
  bad$provenance$engine_semantics_id <- "vbpm_pefa_engine_0.8"
  expect_error(.vfy(bad),
               "`$provenance$engine_semantics_id` is \"vbpm_pefa_engine_0.8\"",
               fixed = TRUE)
  expect_error(.vfy(bad), "vbpm_pefa_engine_0.9", fixed = TRUE)

  ## A schema mismatch is refused outright: the payload of a foreign schema is
  ## not this package's to rebuild or rehash, so no integrity check runs.
  bad <- .vfy_obj
  bad$provenance$evidence_schema_id <- "vbpm_pefa_evidence_0"
  bad$persistence$phi_min[1] <- 0.5
  message <- tryCatch(.vfy(bad), error = conditionMessage)
  expect_match(message, "evidence_schema_id", fixed = TRUE)
  expect_false(grepl("integrity check", message, fixed = TRUE))
})

test_that("a malformed object is refused with a controlled message", {
  expect_error(.vfy(list(a = 1)), "must be a \"pefa\" object", fixed = TRUE)

  bad <- .vfy_obj
  bad$transitions <- NULL
  expect_error(.vfy(bad), "missing component(s) `$transitions`", fixed = TRUE)

  ## An appended component is invisible to every hash -- the payload is
  ## assembled by name -- so the shape itself has to be checked.
  bad <- .vfy_obj
  bad$selected_K <- 2L
  expect_error(.vfy(bad), "unexpected component(s) `$selected_K`",
               fixed = TRUE)

  bad <- structure(unclass(.vfy_obj)[c(2:8, 1)], class = "pefa")
  expect_error(.vfy(bad), "the components are out of order", fixed = TRUE)

  bad <- .vfy_obj
  bad$provenance$lineage_sha256 <- NULL
  expect_error(.vfy(bad), "twelve fields", fixed = TRUE)

  bad <- .vfy_obj
  bad$provenance$evidence_sha256 <- NA_character_
  expect_error(.vfy(bad), "`$provenance$evidence_sha256` must be one",
               fixed = TRUE)

  bad <- .vfy_obj
  bad$provenance$newly_fitted_K <- "1"
  expect_error(.vfy(bad), "`$provenance$newly_fitted_K` must be an integer",
               fixed = TRUE)

  bad <- .vfy_obj
  bad$provenance$parent_evidence_sha256 <- NA
  expect_error(.vfy(bad), "`$provenance$parent_evidence_sha256` must be one",
               fixed = TRUE)

  bad <- .vfy_obj
  bad$sweep <- list(K = 1:3)
  expect_error(.vfy(bad), "`$sweep` must be a data frame", fixed = TRUE)

  bad <- .vfy_obj
  bad$Q0 <- as.vector(bad$Q0)
  expect_error(.vfy(bad), "`$Q0` must be a matrix", fixed = TRUE)

  bad <- .vfy_obj
  bad$settings$stability_eps <- NULL
  expect_error(.vfy(bad), "`$settings` is missing", fixed = TRUE)
})

test_that("supplied data must reproduce the standardized-data hash", {
  expect_error(.vfy(.vfy_obj, .vfy_dat$Y + 1),
               "`Y` does not reproduce `$provenance$standardized_data_sha256`",
               fixed = TRUE)

  ## Column order is part of the fingerprint: the same numbers permuted are a
  ## different fitted input.
  expect_error(.vfy(.vfy_obj, .vfy_dat$Y[, c(2:6, 1)]),
               "`Y` does not reproduce", fixed = TRUE)

  ## An unusable Y is a call problem, not an integrity finding.
  expect_error(.vfy(.vfy_obj, "nope"), "`Y` cannot be standardized",
               fixed = TRUE)
})

test_that("elapsed secs is outside the verified payload", {
  ## A byte-identical rerun on a slower machine is not a mutation.
  slower <- .vfy_obj
  slower$sweep$secs <- slower$sweep$secs + 99
  expect_true(.vfy(slower))
  expect_true(.vfy(slower, .vfy_dat$Y))
})

test_that("the rebuild handles the structural edge cases", {
  ## Bifactor: the rebuild has to reapply the group-block offset, or every
  ## persistence cell comes back shifted by the general column.
  bifac <- suppressWarnings(
    pefa(.vfy_dat$Q0, .vfy_dat$Y, 1, 2, bifactor = TRUE, general = 1,
         v0 = .001, max_it = 300, verbose = FALSE)
  )
  expect_true(.vfy(bifac))
  expect_true(.vfy(bifac, .vfy_dat$Y))
  moved <- bifac
  moved$loadings[[2]][1, 2] <- moved$loadings[[2]][1, 2] + .4
  expect_error(.vfy(moved), "`$persistence` disagrees", fixed = TRUE)

  ## A one-candidate window has no transition and no pair: both builders
  ## return their empty tables and the empty tables must verify too.
  single <- suppressWarnings(
    pefa(.vfy_dat$Q0, .vfy_dat$Y, 2, 2, v0 = .001, max_it = 300,
         verbose = FALSE)
  )
  expect_identical(nrow(single$transitions), 0L)
  expect_identical(nrow(single$persistence), 0L)
  expect_true(.vfy(single))
  expect_true(.vfy(single, .vfy_dat$Y))
})

test_that("table comparison follows the documented policy", {
  cmp <- vbpm:::.pefa_verify_table
  stored <- .vfy_obj$persistence
  expect_null(cmp(stored, stored))

  ## Double metric cells: 1e-10, as ?verify_pefa states.
  near <- stored
  near$phi_min[1] <- near$phi_min[1] + 1e-14
  expect_null(cmp(stored, near))

  far <- stored
  far$phi_min[1] <- far$phi_min[1] + 1e-6
  expect_match(cmp(stored, far), "column `phi_min` differs beyond tolerance",
               fixed = TRUE)

  ## Everything else is identical(), with no tolerance at all.
  counted <- stored
  counted$n_pairs[1] <- counted$n_pairs[1] + 1L
  expect_match(cmp(stored, counted), "column `n_pairs` is not identical",
               fixed = TRUE)

  flagged <- stored
  flagged$collision[1] <- !flagged$collision[1]
  expect_match(cmp(stored, flagged), "column `collision` is not identical",
               fixed = TRUE)

  reasoned <- stored
  reasoned$pair_status[1] <- "unavailable"
  expect_match(cmp(stored, reasoned), "column `pair_status` is not identical",
               fixed = TRUE)

  ## The NA pattern is structure, not a value: it never gets the tolerance.
  blanked <- stored
  blanked$rmsd[1] <- NA_real_
  expect_match(cmp(stored, blanked), "column `rmsd` has a different NA pattern",
               fixed = TRUE)

  renamed <- stored
  names(renamed)[5] <- "phi"
  expect_match(cmp(stored, renamed), "column names", fixed = TRUE)

  shortened <- stored[-1, , drop = FALSE]
  expect_match(cmp(shortened, stored), "row count or row names", fixed = TRUE)

  retyped <- stored
  retyped$n_pairs <- as.double(retyped$n_pairs)
  expect_match(cmp(retyped, stored), "storage mode differs", fixed = TRUE)
})

test_that("the shipped integrity fixture verifies both ways", {
  path <- system.file("extdata", "vbpm_r8_fixture.rds", package = "vbpm")
  if (!nzchar(path) || !file.exists(path)) {
    skip("inst/extdata/vbpm_r8_fixture.rds is not installed.")
  }
  integrity <- readRDS(path)[["integrity"]]
  if (is.null(integrity)) {
    skip("The fixture carries no integrity case yet.")
  }
  expect_true(.vfy(integrity[["object"]]))
  expect_true(.vfy(integrity[["object"]], integrity[["Y"]]))
})

test_that("verify_pefa is exported once NAMESPACE is regenerated", {
  if (!("verify_pefa" %in% getNamespaceExports("vbpm"))) {
    skip("NAMESPACE has not yet been regenerated from the @export tag.")
  }
  expect_true(is.function(vbpm::verify_pefa))
  expect_identical(names(formals(vbpm::verify_pefa)), c("x", "Y"))
})
