// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// my_quic_cpp
arma::cube my_quic_cpp(int J, arma::mat S, arma::mat Rho, double eps, int max_iter_quic);
RcppExport SEXP _vbpm_my_quic_cpp(SEXP JSEXP, SEXP SSEXP, SEXP RhoSEXP, SEXP epsSEXP, SEXP max_iter_quicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Rho(RhoSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter_quic(max_iter_quicSEXP);
    rcpp_result_gen = Rcpp::wrap(my_quic_cpp(J, S, Rho, eps, max_iter_quic));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_vbpm_my_quic_cpp", (DL_FUNC) &_vbpm_my_quic_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_vbpm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
